### ISSUE TITLE
pytest plugin

### ISSUE THREAD

**Issue by rochacbruno** [slaily/pyhttptest#1]
I suggest a pytest plugin to allow the following.

```bash
pip install pytest-pyhttptest
```

The above installs the pytest plugin and the `httptest` fixture.

```python
def test_get(httptest):
    httptest.run(either a json file path, or a json string)
```

Why?

The advantege is that this goes together with pytest reports

**Comment by slaily** [comment]
Hello @rochacbruno,

I think we can do that, but I don't want to mix it up with this package. Because pyhttptest purpose is only one just a command-line tool. The idea is very good and I totally agree with you. We can do it on a separate project!

Once again thank you!

Contact me for more about pytest-pyhttptest if you want.
